---
engines:
  rubocop:
    enabled: true
  brakeman:
    enabled: true
ratings:
  paths:
  - app/**/*
  - "**.rb"
  - "**.coffee"
  - "**.js"
  - "**.jsx"
  - "**.css"
exclude_paths:
- config/**/*
- db/**/*
- controllers/**/*
- script/**/*
- spec/**/*
- test/**/*
- vendor/**/*
